[project]
name = "ts-elasticspheres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Babakkhodabandeloo", email = "khodabandeloo.babak@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pyqt6>=6.11.0",
    "scipy>=1.18.1",
    "streamlit>=1.64.0",
]

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
